name: unified_latent

num_iters: 50

schedule: timestep
rho_min: null
rho_max: null

method: hmc
sample_num_iters: 30
sample_learning_rate: 1e-4
sample_momentum: 0.45

skip_noising: false

num_burn_in_iters: 40
num_samples_per_run: 20
